formatter: "" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: 
    - requirements
    - modules
  show: []

  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true  # deprecated in v0.13.0, removed in v0.15.0

content: |-
    {{ .Header }}
    ### Example AlmaLinux 8

    ```hcl
    {{ include "examples/almalinux8/main.tf" }}
    ```

    ### Example AlmaLinux 9

    ```hcl
    {{ include "examples/almalinux9/main.tf" }}
    ```

    ### Example RockyLinux 8

    ```hcl
    {{ include "examples/rockylinux8/main.tf" }}
    ```

    ### Example RockyLinux 9

    ```hcl
    {{ include "examples/rockylinux9/main.tf" }}
    ```

    ### Example FreeBSD 13.1

    ```hcl
    {{ include "examples/freebsd131/main.tf" }}
    ```
   
    ### Example OpenMandriva 

    ```hcl
    {{ include "examples/openmandriva/main.tf" }}
    ```
   
    ### Example OracleLinux 7.9

    ```hcl
    {{ include "examples/oraclelinux79/main.tf" }}
    ```

    ### Example OracleLinux 8

    ```hcl
    {{ include "examples/oraclelinux8/main.tf" }}
    ```

    ### Example OracleLinux 9

    ```hcl
    {{ include "examples/oraclelinux9/main.tf" }}
    ```

    ### Example Ubuntu 18.04

    ```hcl
    {{ include "examples/ubuntu1804/main.tf" }}
    ```

    ### Example Ubuntu 20.04

    ```hcl
    {{ include "examples/ubuntu2004/main.tf" }}
    ```

    ### Example Ubuntu 22.04

    ```hcl
    {{ include "examples/ubuntu2204/main.tf" }}
    ```
    
    {{ .Data-sources }}
    {{ .Inputs }}
    {{ .Outputs }}  
    {{ .Resources }}  
    {{ .Footer }}  

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->    

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
