name: Generate terraform docs
on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Documenation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.1.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
