name: Generate terraform docs
on:
  push:
    branches:
      - main
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.4.1
      with:
        working-dir: .
        output-file: README.md
        config-file: .terraform-docs.yml
        output-method: inject
        git-push: "true"
